package core

import (
	"strings"
	"time"
	"unicode"
)

// Sanitize removes non-printable characters from a string, keeping newlines, carriage returns, and tabs.
func Sanitize(s string) string {
	return strings.Map(func(r rune) rune {
		if unicode.IsPrint(r) || r == '\n' || r == '\r' || r == '\t' {
			return r
		}
		return -1
	}, s)
}

// EscapeMarkdown escapes characters that have special meaning in Markdown.
func EscapeMarkdown(s string) string {
	replacer := strings.NewReplacer(
		"\\", "\\\\",
		"`", "\\`",
		"*", "\\*",
		"_", "\\_",
		"{", "\\{",
		"}", "\\}",
		"[", "\\[",
		"]", "\\]",
	)
	return replacer.Replace(s)
}

// FormatDate standardizes dates to "YYYY-MM-DD HH:MM:SS UTC"
func FormatDate(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.UTC().Format("2006-01-02 15:04:05 UTC")
}

// Evidence represents the raw, unmodified metadata and content of an email message.
type Evidence struct {
	ID       int
	Folder   string // Used for PST/MBOX folder mapping
	From     string
	To       string
	Date     string
	Subject  string
	BodyText string
	BodyHTML string
	Headers  string
}

// Attachment represents a file attached to an Evidence item.
type Attachment struct {
	ID         int
	EvidenceID int
	Filename   string
	Size       int64
	MD5        string
	SHA256     string
}

// Enrichment represents data generated by our analysis plugins.
type Enrichment struct {
	ID         int
	EvidenceID int
	PluginName string
	Data       string
}

// Plugin defines the interface that all Enricher plugins must implement.
type Plugin interface {
	Name() string
	Type() string
	TargetFormat() string
	Description() string
	Process(evidence *Evidence) ([]Enrichment, error)
}
