package database

import (
	"Bibliorato/core"
	"database/sql"
	"fmt"

	_ "modernc.org/sqlite"
)

var db *sql.DB

// InitDB initializes the SQLite database and creates the necessary tables
// for the "Layered Integrity" schema.
func InitDB(filepath string) error {
	var err error
	db, err = sql.Open("sqlite", filepath)
	if err != nil {
		return err
	}

	return createTables()
}

func createTables() error {
	// Layered Integrity Schema: strict separation of pristine evidence vs enrichments.
	evidenceTable := `
	CREATE TABLE IF NOT EXISTS evidence (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		folder TEXT,
		sender TEXT,
		recipient TEXT,
		date TEXT,
		subject TEXT,
		body_text TEXT,
		body_html TEXT,
		headers TEXT
	);`

	attachmentsTable := `
	CREATE TABLE IF NOT EXISTS attachments (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		evidence_id INTEGER,
		filename TEXT,
		size INTEGER,
		md5 TEXT,
		sha256 TEXT,
		data BLOB,
		FOREIGN KEY(evidence_id) REFERENCES evidence(id)
	);`

	enrichmentsTable := `
	CREATE TABLE IF NOT EXISTS enrichments (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		evidence_id INTEGER,
		plugin_name TEXT,
		data TEXT,
		FOREIGN KEY(evidence_id) REFERENCES evidence(id)
	);`

	_, err := db.Exec(evidenceTable)
	if err != nil {
		return fmt.Errorf("error creating evidence table: %v", err)
	}

	_, err = db.Exec(attachmentsTable)
	if err != nil {
		return fmt.Errorf("error creating attachments table: %v", err)
	}

	_, err = db.Exec(enrichmentsTable)
	if err != nil {
		return fmt.Errorf("error creating enrichments table: %v", err)
	}

	return nil
}

// InsertEvidence stores raw, unmodified email metadata.
func InsertEvidence(e *core.Evidence) (int64, error) {
	stmt, err := db.Prepare("INSERT INTO evidence(folder, sender, recipient, date, subject, body_text, body_html, headers) VALUES(?, ?, ?, ?, ?, ?, ?, ?)")
	if err != nil {
		return 0, err
	}
	defer stmt.Close()

	res, err := stmt.Exec(e.Folder, e.From, e.To, e.Date, e.Subject, e.BodyText, e.BodyHTML, e.Headers)
	if err != nil {
		return 0, err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return 0, err
	}

	return id, nil
}

// InsertAttachment stores an attachment in the database.
func InsertAttachment(a *core.Attachment, data []byte) (int64, error) {
	stmt, err := db.Prepare("INSERT INTO attachments(evidence_id, filename, size, md5, sha256, data) VALUES(?, ?, ?, ?, ?, ?)")
	if err != nil {
		return 0, err
	}
	defer stmt.Close()

	res, err := stmt.Exec(a.EvidenceID, a.Filename, a.Size, a.MD5, a.SHA256, data)
	if err != nil {
		return 0, err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return 0, err
	}

	return id, nil
}

// GetAttachmentsByEvidenceID retrieves attachments metadata for a specific evidence item.
func GetAttachmentsByEvidenceID(evidenceID int) ([]core.Attachment, error) {
	rows, err := db.Query("SELECT id, evidence_id, filename, size, md5, sha256 FROM attachments WHERE evidence_id = ?", evidenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var attList []core.Attachment
	for rows.Next() {
		var a core.Attachment
		err = rows.Scan(&a.ID, &a.EvidenceID, &a.Filename, &a.Size, &a.MD5, &a.SHA256)
		if err != nil {
			return nil, err
		}
		attList = append(attList, a)
	}
	return attList, nil
}

// GetAttachmentData retrieves the binary data for a specific attachment.
func GetAttachmentData(attachmentID int) ([]byte, error) {
	var data []byte
	err := db.QueryRow("SELECT data FROM attachments WHERE id = ?", attachmentID).Scan(&data)
	if err != nil {
		return nil, err
	}
	return data, nil
}

// InsertEnrichment stores data generated by an analysis plugin.
func InsertEnrichment(en *core.Enrichment) (int64, error) {
	stmt, err := db.Prepare("INSERT INTO enrichments(evidence_id, plugin_name, data) VALUES(?, ?, ?)")
	if err != nil {
		return 0, err
	}
	defer stmt.Close()

	res, err := stmt.Exec(en.EvidenceID, en.PluginName, en.Data)
	if err != nil {
		return 0, err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return 0, err
	}

	return id, nil
}

// GetAllEvidence retrieves all evidence from the database.
func GetAllEvidence() ([]core.Evidence, error) {
	rows, err := db.Query("SELECT id, folder, sender, recipient, date, subject, body_text, body_html, headers FROM evidence")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	return scanEvidenceRows(rows)
}

// GetEvidenceByFolder retrieves evidence items matching a specific folder name.
func GetEvidenceByFolder(folderName string) ([]core.Evidence, error) {
	rows, err := db.Query("SELECT id, folder, sender, recipient, date, subject, body_text, body_html, headers FROM evidence WHERE folder = ?", folderName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	return scanEvidenceRows(rows)
}

// GetEvidenceCount returns the total number of evidence items for a given folder (or all if folder is empty).
func GetEvidenceCount(folderName string) (int, error) {
	var count int
	var err error
	if folderName == "" {
		err = db.QueryRow("SELECT COUNT(*) FROM evidence").Scan(&count)
	} else {
		err = db.QueryRow("SELECT COUNT(*) FROM evidence WHERE folder = ?", folderName).Scan(&count)
	}
	return count, err
}

// GetEvidenceByIndex returns a single evidence item at the specified offset (0-based) for a given folder.
func GetEvidenceByIndex(index int, folderName string) (*core.Evidence, error) {
	var query string
	var args []interface{}

	if folderName == "" {
		query = "SELECT id, folder, sender, recipient, date, subject, body_text, body_html, headers FROM evidence ORDER BY id LIMIT 1 OFFSET ?"
		args = []interface{}{index}
	} else {
		query = "SELECT id, folder, sender, recipient, date, subject, body_text, body_html, headers FROM evidence WHERE folder = ? ORDER BY id LIMIT 1 OFFSET ?"
		args = []interface{}{folderName, index}
	}

	row := db.QueryRow(query, args...)
	return scanEvidenceRow(row)
}

func scanEvidenceRow(row *sql.Row) (*core.Evidence, error) {
	var e core.Evidence
	err := row.Scan(&e.ID, &e.Folder, &e.From, &e.To, &e.Date, &e.Subject, &e.BodyText, &e.BodyHTML, &e.Headers)
	if err != nil {
		return nil, err
	}
	return &e, nil
}

func scanEvidenceRows(rows *sql.Rows) ([]core.Evidence, error) {
	var evList []core.Evidence
	for rows.Next() {
		var e core.Evidence
		err := rows.Scan(&e.ID, &e.Folder, &e.From, &e.To, &e.Date, &e.Subject, &e.BodyText, &e.BodyHTML, &e.Headers)
		if err != nil {
			return nil, err
		}
		evList = append(evList, e)
	}
	return evList, nil
}

// GetEnrichmentsByEvidenceID retrieves enrichments for a specific evidence item.
func GetEnrichmentsByEvidenceID(evidenceID int) ([]core.Enrichment, error) {
	rows, err := db.Query("SELECT id, evidence_id, plugin_name, data FROM enrichments WHERE evidence_id = ?", evidenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var enList []core.Enrichment
	for rows.Next() {
		var en core.Enrichment
		err = rows.Scan(&en.ID, &en.EvidenceID, &en.PluginName, &en.Data)
		if err != nil {
			return nil, err
		}
		enList = append(enList, en)
	}
	return enList, nil
}

// CloseDB gracefully closes the database connection.
func CloseDB() error {
	if db != nil {
		return db.Close()
	}
	return nil
}

// ClearDB removes all records from all tables to prepare for a new file.
func ClearDB() error {
	if db == nil {
		return fmt.Errorf("database not initialized")
	}

	// Order matters due to foreign keys if we had strict enforcement,
	// but DELETE FROM with no WHERE is efficient.
	tables := []string{"enrichments", "attachments", "evidence"}
	for _, table := range tables {
		_, err := db.Exec(fmt.Sprintf("DELETE FROM %s", table))
		if err != nil {
			return fmt.Errorf("failed to clear table %s: %w", table, err)
		}
		// Reset autoincrement (ignore error if sequence table doesn't exist for this table)
		_, _ = db.Exec("DELETE FROM sqlite_sequence WHERE name=?", table)
	}

	return nil
}
